### List Slicing

In [ ]:
nums = [i**2 for i in range(10)] # list comprehension
print(nums)
len(nums)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


10

In [ ]:
for i in nums:
  print(i)

In [ ]:
first_nums = nums[0:5]
# last_nums = nums[]
print(first_nums)
last_nums = nums[5:]
print(last_nums)

arr = nums[:]
print(arr)

In [ ]:
odd_nums = nums[1::2]
print(odd_nums)

print(nums[-1])

reverse_nums = nums[::-1]
print(reverse_nums)

### Tuple

In [ ]:
coordinates = (5,0)
marks = [('A',90),('A-',86)]
print(coordinates[0])
print(marks[1][0])
# coordinates[1] = 4

### Dictionary

In [ ]:
student = {
    'name':'Rahim',
    'id':2,
    'cgpa':3.73,
    'courses':['AI','OS','DBMS'],
    8:'trimester'
}

In [ ]:
student['blood group'] = 'A+'
student['cgpa'] = 3.76

In [1]:
student
print(student.keys())
print(student.values())
print(student.items())

NameError: name 'student' is not defined

In [ ]:
for key in student:
  print(key,student[key])

In [ ]:
for k,v in student.items():
  print(k,v)

In [ ]:
student['name']

In [ ]:
student.get('id')

### Object

In [ ]:
class student:
  def __init__(self,name,id,cgpa,trimester):
    self.name = name
    self.id = id
    self.__cgpa = cgpa
    self.trimester = trimester


  def getCgpa(self):
    return self.__cgpa
  @staticmethod
  def study():
    print("Studying!!")

  def __str__(self):
    return self.name + " " + str(self. id) + " " + (self.trimester)


st = student('Rahim',10,3.85,'5th')
print(st.name)
print(st.getCgpa())
student.study()
print(st)


Rahim
3.85
Studying!!
Rahim 10 5th


## Numpy Library

In [5]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
print(type(lst1),type(lst2))
lst1+lst2

<class 'list'> <class 'list'>


[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]

In [3]:
# pip install numpy
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([2,3,4,5,6])
print(type(arr1),type(arr2))
print(arr1 + arr2)
print(lst1 * 3)
print(arr1 * 3)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[ 3  5  7  9 11]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


In [8]:
print(arr1.shape)

mat = np.array([
    [1,2,3],
    [4,5,6]])
print(mat.shape)

(5,)
(2, 3)


In [9]:
# reshaping an array
print(mat.reshape((6,)))
print(arr1.reshape((1,5)))
print(arr1.reshape((5,1)))

[1 2 3 4 5 6]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
mat = np.random.random((2,2))
print(mat)
int_mat = np.random.randint(10,size=(3,3))
print(int_mat)

[[0.48069599 0.33560703]
 [0.74166247 0.35395043]]
[[0 4 5]
 [2 8 4]
 [2 4 1]]


In [11]:
zero_mat = np.zeros((2,2),dtype = 'int64')
print(zero_mat)
ones_mat = np.ones((2,2))
print(ones_mat)
identity_mat = np.eye(3)
print(identity_mat)

[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Slicing

In [12]:
arr1 = np.array([1,2,3,4,5])
arr1[:3]

array([1, 2, 3])

In [13]:
mat = np.array([
    [1,2,3],
    [4,5,6]]) #[[1,2],[4,5]]

In [14]:
temp = mat[:,:-1]
print(temp)

[[1 2]
 [4 5]]


In [15]:
mat = np.array([
    [1,2,3],
    [4,5,6]]) #[[1,3],[4,6]]
temp = mat[:,::2]
print(temp)

[[1 3]
 [4 6]]


In [16]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]) #[[1,3],[7,9]]
temp = mat[::2,::2]
print(temp)

[[1 3]
 [7 9]]


In [21]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]]) #[[5,6],[8,9]]
temp = mat[1::,1::]
print(temp)

[[5 6]
 [8 9]]


### Axis summation

In [22]:
arr1 = np.array([1,2,3,4,5])
print(np.sum(arr1))

15


In [23]:
mat = np.array([
    [1,2,3],
    [4,5,6]])
print(mat.shape)
print(np.sum(mat))
print(np.sum(mat,axis=0)) # column-wise
print(np.sum(mat,axis=1)) # row-wise

(2, 3)
21
[5 7 9]
[ 6 15]


In [24]:
mat = np.array([
    [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ],
    [
      [1,2,3],
      [4,5,6],
      [7,8,9]
    ]
    ])
print(mat.shape)
print("------------")
print(np.sum(mat,axis=0))
print("------------")
print(np.sum(mat,axis=1))
print("------------")
print(np.sum(mat,axis=2))

(2, 3, 3)
------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
------------
[[12 15 18]
 [12 15 18]]
------------
[[ 6 15 24]
 [ 6 15 24]]
